version: "3.1"
services:
  couchDb:
    build: ./dockerfiles/couchdb.dockerfile
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    ports:
      - 5984:5984
    volumes:
     - ./couchdb-config:/opt/couchdb/etc/local.d/
     - ./couchdb-data:/opt/couchdb/data
    networks:
      - backend
  
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
    command:
      - start-dev
    networks:
      - backend
    volumes:
      - ./keycloak-data/:/opt/keycloak/data/

networks:
  backend:
    name: couchdb-network